server:
  port: 8080
  servlet:
    context-path: /ecommerce-nacos-client

spring:
  application:
    name: e-commerce-nacos-client # 应用名称也是构成 Nacos 配置管理 dataId 字段的一部分 (当 config.prefix 为空时)
  cloud:
    nacos:
      # 服务注册发现
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        # server-addr: 192.168.0.54:8848
        server-addr: 192.168.0.54:8848,192.168.0.54:8858 # Nacos 服务器地址
        namespace: 3471ee14-8415-4f57-be25-36ec3e9eb631
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always