server:
  port: 7001
  servlet:
    context-path: /e-commerce-admin

spring:
  application:
    name: e-commerce-admin
  cloud:
    nacos:
      discovery:
        enabled: true
        # server-addr: 192.168.0.54:8848
        server-addr: 192.168.0.54:8848,192.168.0.54:8858 # Nacos 服务器地址
        namespace: 3471ee14-8415-4f57-be25-36ec3e9eb631
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
  thymeleaf:
    check-template: false
    check-template-location: false

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
  endpoint:
    health:
      show-details: always